# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ca.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'ca.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x63\x61.proto\"#\n\x0b\x43\x41PublicKey\x12\t\n\x01n\x18\x01 \x01(\t\x12\t\n\x01\x64\x18\x02 \x01(\t\"u\n\x0b\x43\x65rtificate\x12\n\n\x02id\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\t\x12\t\n\x01\x65\x18\x03 \x01(\t\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\x12\x10\n\x08\x64uration\x18\x05 \x01(\x03\x12\x0c\n\x04\x63\x61Id\x18\x06 \x01(\t\x12\x11\n\tsignature\x18\x07 \x01(\t\"?\n\x15RegisterClientRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\x12\t\n\x01n\x18\x02 \x01(\t\x12\t\n\x01\x65\x18\x03 \x01(\t\"&\n\x12\x43\x65rtificateRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\"=\n\x18\x43\x65rtificateVerifyRequest\x12!\n\x0b\x63\x65rtificate\x18\x01 \x01(\x0b\x32\x0c.Certificate\",\n\x19\x43\x65rtificateVerifyResponse\x12\x0f\n\x07isValid\x18\x01 \x01(\x08\"&\n\x12\x43\x41PublicKeyRequest\x12\x10\n\x08\x63lientId\x18\x01 \x01(\t\")\n\x16RegisterClientResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"#\n\x10\x45ncryptedMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"#\n\x0f\x41\x63knowledgement\x12\x10\n\x08response\x18\x01 \x01(\t2\x8c\x02\n\tCAService\x12\x41\n\x0eRegisterClient\x12\x16.RegisterClientRequest\x1a\x17.RegisterClientResponse\x12\x37\n\x12RequestCertificate\x12\x13.CertificateRequest\x1a\x0c.Certificate\x12\x37\n\x12RequestCAPublicKey\x12\x13.CAPublicKeyRequest\x1a\x0c.CAPublicKey\x12J\n\x11VerifyCertificate\x12\x19.CertificateVerifyRequest\x1a\x1a.CertificateVerifyResponse2Z\n\x16MessageExchangeService\x12@\n\x17ReceiveEncryptedMessage\x12\x11.EncryptedMessage\x1a\x10.Acknowledgement\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ca_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CAPUBLICKEY']._serialized_start=12
  _globals['_CAPUBLICKEY']._serialized_end=47
  _globals['_CERTIFICATE']._serialized_start=49
  _globals['_CERTIFICATE']._serialized_end=166
  _globals['_REGISTERCLIENTREQUEST']._serialized_start=168
  _globals['_REGISTERCLIENTREQUEST']._serialized_end=231
  _globals['_CERTIFICATEREQUEST']._serialized_start=233
  _globals['_CERTIFICATEREQUEST']._serialized_end=271
  _globals['_CERTIFICATEVERIFYREQUEST']._serialized_start=273
  _globals['_CERTIFICATEVERIFYREQUEST']._serialized_end=334
  _globals['_CERTIFICATEVERIFYRESPONSE']._serialized_start=336
  _globals['_CERTIFICATEVERIFYRESPONSE']._serialized_end=380
  _globals['_CAPUBLICKEYREQUEST']._serialized_start=382
  _globals['_CAPUBLICKEYREQUEST']._serialized_end=420
  _globals['_REGISTERCLIENTRESPONSE']._serialized_start=422
  _globals['_REGISTERCLIENTRESPONSE']._serialized_end=463
  _globals['_ENCRYPTEDMESSAGE']._serialized_start=465
  _globals['_ENCRYPTEDMESSAGE']._serialized_end=500
  _globals['_ACKNOWLEDGEMENT']._serialized_start=502
  _globals['_ACKNOWLEDGEMENT']._serialized_end=537
  _globals['_CASERVICE']._serialized_start=540
  _globals['_CASERVICE']._serialized_end=808
  _globals['_MESSAGEEXCHANGESERVICE']._serialized_start=810
  _globals['_MESSAGEEXCHANGESERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
